def build_manim_prompt(user_text: str) -> str:
    return f"""
You are an expert Manim developer.

TASK:
Generate ONLY valid Python Manim code.
Do NOT explain anything.
Do NOT add markdown.
Do NOT add comments outside code.
Do NOT add text before or after code.

RULES:
- Use Manim Community Edition
- Import from manim
- Create ONE Scene class
- Scene name: AutoGeneratedScene
- Use clear animations
- Ensure code is runnable
- No syntax errors
- No placeholders

SCENE DESCRIPTION:
{user_text}

OUTPUT:
(Python code only)
"""
